/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Emergencyclasses.Location;
import Emergencyclasses.Sensor;
import Emergencyclasses.SensorMonitor;
import Emergencyclasses.SetOfLocation;
import Validations.Validation;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import serialization.Serialization;

/**
 *
 * @author Piyu
 */
public class AddEmergencySensor extends javax.swing.JFrame {

    /**
     * Creates new form AddEmergencySensor
     */
     public static final String FILE_NAME_Sensor = "DataFiles/EmergencySensors.txt";
       public static final String FILE_NAME_Location = "DataFiles/EmergencySensorsLocation.txt";
     private  SensorMonitor sensorSet = new SensorMonitor();
     private SetOfLocation locationSet = new SetOfLocation();
    private Double setLatitude;
    private Double setLongitude;
            Validation validation = new Validation() ; 
    public AddEmergencySensor() {
        initComponents();
            load();
            loadLocation();
           //   add.disable();
    }
    
      public AddEmergencySensor(Double setLatitudes ,Double setLongitudes) {
        initComponents();
                    this.setLatitude = setLatitudes;
               this.setLongitude = setLongitudes;
            System.err.println(this.setLatitude);
            System.err.println(this.setLongitude);
                load();
                   loadLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtanpDes = new javax.swing.JTextField();
        txtanpName = new javax.swing.JTextField();
        statusText = new javax.swing.JComboBox<>();
        reset1 = new javax.swing.JButton();
        txtanpId = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        frequencyText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblanpSensor = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 830));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 330, 140, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setText("Description");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 380, 140, 30);

        txtanpDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanpDesActionPerformed(evt);
            }
        });
        getContentPane().add(txtanpDes);
        txtanpDes.setBounds(190, 380, 250, 30);

        txtanpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanpNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtanpName);
        txtanpName.setBounds(190, 330, 250, 30);

        statusText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Non-Active" }));
        getContentPane().add(statusText);
        statusText.setBounds(190, 432, 250, 30);

        reset1.setBackground(new java.awt.Color(0, 102, 153));
        reset1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        reset1.setForeground(new java.awt.Color(255, 255, 255));
        reset1.setText("Remove");
        reset1.setContentAreaFilled(false);
        reset1.setOpaque(true);
        reset1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset1MouseClicked(evt);
            }
        });
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1);
        reset1.setBounds(320, 540, 120, 40);

        txtanpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanpIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtanpId);
        txtanpId.setBounds(190, 270, 250, 40);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setText("Sensor ID");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 270, 140, 30);

        add.setBackground(new java.awt.Color(0, 102, 153));
        add.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.setContentAreaFilled(false);
        add.setOpaque(true);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(40, 540, 120, 40);

        reset.setBackground(new java.awt.Color(0, 102, 153));
        reset.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Update");
        reset.setContentAreaFilled(false);
        reset.setOpaque(true);
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(180, 540, 120, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 30, 30, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("www.Agrivi.com/addemergencysensor.html");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(170, 20, 327, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("Status");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 430, 120, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setText("Frequency");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 480, 130, 30);

        frequencyText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                frequencyTextKeyTyped(evt);
            }
        });
        getContentPane().add(frequencyText);
        frequencyText.setBounds(190, 480, 250, 30);

        tblanpSensor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblanpSensor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblanpSensorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblanpSensor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 310, 760, 280);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kk.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 80, 380, 120);

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("    Bin Sensor");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 200, 160, 50);

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Flood Sensor");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(850, 200, 190, 50);

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel13.setText("Emergency Sensor");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(620, 200, 220, 50);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 210, 520, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-5, 0, 1830, 810);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
 String name, description , frequency ,status;
     
          if (txtanpName.getText().isEmpty()) {
                  JOptionPane.showMessageDialog(this, "Please provide name...", "Error", JOptionPane.ERROR_MESSAGE);
         
        }
        
        else if (txtanpDes.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide Description...", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (frequencyText.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide frequency...", "Error", JOptionPane.ERROR_MESSAGE);
        }

        else {
            name = txtanpName.getText();
            description = txtanpDes.getText();
            frequency =  frequencyText.getText();
            status = (String) statusText.getSelectedItem() ; 
            //            Icon icon = imageIcon.getIcon();

            sensorSet.addNewSensor(new Sensor(name, description, Double.parseDouble(frequency),status));

            
            try {
                Serialization.Serialize(sensorSet, FILE_NAME_Sensor);
                System.out.println("Add Sucsessfully");
                 JOptionPane.showMessageDialog(this, "You have Added successfully", "Message", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                //                Logger.getLogger(AddNewProduct.class.getName()).log(Level.SEVERE, null, ex);
                //                JOptionPane.showMessageDialog(this, "Unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Unsuccessful...");
                JOptionPane.showMessageDialog(this,"submission failed ", "Error", JOptionPane.ERROR_MESSAGE);
            }

            loadAddSensor(sensorSet);

            
            Sensor sensor = sensorSet.getSensorFromName(txtanpName.getText()).firstElement();
//            sensorSet.addNewSensorLocation(sensor.getSensorNo(), 55.2, 55.2);
            locationSet.addNewSensor(new Location(this.setLatitude,this.setLongitude,sensor.getSensorNo())); 
 
             try {
                Serialization.Serialize(locationSet, FILE_NAME_Location);

                System.out.println("Add Sucsessfully");

            } catch (IOException ex) {
                //                Logger.getLogger(AddNewProduct.class.getName()).log(Level.SEVERE, null, ex);
                //                JOptionPane.showMessageDialog(this, "Unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Unsuccessful...");
            }
            
        }
    }//GEN-LAST:event_addMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
                String name, description , state;
               double freq; 
              
              name = txtanpName.getText();
              description = txtanpDes.getText();
                 freq  = Double.parseDouble(frequencyText.getText());
                 state = statusText.getSelectedItem().toString();
        
           Sensor sensor = sensorSet.getSensorFromID(Integer.parseInt(txtanpId.getText())).firstElement();

            String status = sensorSet.updateSensors(sensor, name, description , freq,state);
            System.out.println(status);
               if (status.equals("success")) {
                    try {
                        Serialization.Serialize(sensorSet, FILE_NAME_Sensor);
                    } catch (IOException ex) {
                        Logger.getLogger(AddSensor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "You have updated successful", "Message", JOptionPane.INFORMATION_MESSAGE);
                  //  clear();
                    loadAddSensor(sensorSet);

                } else {
                    JOptionPane.showMessageDialog(this, "Update unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }          
    }//GEN-LAST:event_resetMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_resetActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        EmergencySensorStation h = new EmergencySensorStation();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtanpDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanpDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanpDesActionPerformed

    private void txtanpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanpNameActionPerformed

    private void txtanpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanpIdActionPerformed

    private void reset1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset1MouseClicked
         Sensor sensor = sensorSet.getSensorFromID(Integer.parseInt(txtanpId.getText())).firstElement();
                System.out.println("delete product" + sensor);
                
                  if (sensorSet.remove(sensor)) {
                      Location location   = locationSet.getLocationFromSensorID(sensor.getSensorNo()).firstElement();
                      locationSet.remove(location);
                    try {
                        Serialization.Serialize(sensorSet, FILE_NAME_Sensor);
                         Serialization.Serialize(locationSet, FILE_NAME_Location);
                    } catch (IOException ex) {
                        Logger.getLogger(AddSensor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    loadAddSensor(sensorSet);
                    JOptionPane.showMessageDialog(this, "Delete Sucsessfully", "Message", JOptionPane.PLAIN_MESSAGE);
                

                } else {
                    JOptionPane.showMessageDialog(this, "Delete unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                }

        // TODO add your handling code here:
    }//GEN-LAST:event_reset1MouseClicked

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1ActionPerformed

    private void tblanpSensorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblanpSensorMouseClicked
      DefaultTableModel dtModel= (DefaultTableModel) tblanpSensor.getModel();
           int row = tblanpSensor.getSelectedRow();
        txtanpId.setText(tblanpSensor.getValueAt(row, 0).toString());
        txtanpName.setText(tblanpSensor.getValueAt(row, 1).toString());
        txtanpDes.setText(tblanpSensor.getValueAt(row, 3).toString());
          frequencyText.setText(tblanpSensor.getValueAt(row, 4).toString());
          statusText.setSelectedItem(tblanpSensor.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblanpSensorMouseClicked

    private void frequencyTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frequencyTextKeyTyped
         validation.validateNumber(frequencyText,evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_frequencyTextKeyTyped

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
         BinSensor binSensor = new BinSensor();
         binSensor.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
         FloodSensor floodSensor = new FloodSensor();
         floodSensor.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked
  private void loadAddSensor(SensorMonitor sensorMoni) {

        String[] colName = {"SensorID", "Name", "Status", "Description",  "Frequency"};
        Object[][] object = new Object[sensorMoni.size()][6];
        int i = 0;
        if (sensorMoni.size() != 0) {
            for (Sensor sensors : sensorMoni) {
                object[i][0] = sensors.getSensorNo();
                object[i][1] = sensors.getName();
                object[i][2] = sensors.getStatus();
                object[i][3] = sensors.getdescription();
                object[i][4] = sensors.getfrequency();
                i++;

            }
        }

        DefaultTableModel model = new DefaultTableModel(object, colName) {
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        tblanpSensor.setModel(model);
        tblanpSensor.setRowSorter(new TableRowSorter<TableModel>(model));
        tblanpSensor.setAutoscrolls(true);
        tblanpSensor.getTableHeader().setReorderingAllowed(false);

    }
       public void load(){
        try { 
             for (Sensor sensors : Serialization.deserializeEmergencySensors()) {
                         sensorSet.addNewSensor(sensors);
                       
//                          products.print();
            }
        } catch (IOException | ClassNotFoundException  ex) {
            JOptionPane.showMessageDialog(this, ex);
        
        }
       
          loadAddSensor(sensorSet);
    }
         public void loadLocation(){
        try { 
             for (Location location : Serialization.deserializeEmergencySensorsLocation()) {
                         locationSet.addNewSensor(location);
//                          products.print();
            }
        } catch (IOException | ClassNotFoundException  ex) {
            JOptionPane.showMessageDialog(this, ex);
        
        }
         
//          loadAddSensor(sensorSet);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmergencySensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmergencySensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmergencySensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmergencySensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmergencySensor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField frequencyText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JComboBox<String> statusText;
    private javax.swing.JTable tblanpSensor;
    private javax.swing.JTextField txtanpDes;
    private javax.swing.JTextField txtanpId;
    private javax.swing.JTextField txtanpName;
    // End of variables declaration//GEN-END:variables
}
