/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Product;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import serialization.Serialization;

/**
 *
 * @author wolf
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
     public static ProductsImp products = new ProductsImp();
    public static final String FILE_NAME_Products = "DataFiles/Products.txt";
    private SetOfProducts productSet = new SetOfProducts();
    private Serialization serialize = new Serialization();
    JFileChooser chooser;
    FileNameExtensionFilter filter;
    FileInputStream fis;
    /**
     * Creates new form AddNewProduct
     */
    String username,userLevel,email;
    String workingDir = System.getProperty("user.dir");
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtanpId = new javax.swing.JTextField();
        txtanpName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtanpDes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnancSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblanpProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("ProductID         :");

        txtanpId.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtanpId.setForeground(new java.awt.Color(102, 102, 102));
        txtanpId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtanpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanpIdActionPerformed(evt);
            }
        });

        txtanpName.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtanpName.setForeground(new java.awt.Color(102, 102, 102));
        txtanpName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtanpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanpNameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Name               :");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Description       :");

        txtanpDes.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtanpDes.setForeground(new java.awt.Color(102, 102, 102));
        txtanpDes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Image              :");

        btnancSave.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        btnancSave.setForeground(new java.awt.Color(102, 102, 102));
        btnancSave.setText("Add");
        btnancSave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnancSave.setContentAreaFilled(false);
        btnancSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnancSaveMouseClicked(evt);
            }
        });
        btnancSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnancSaveActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tblanpProduct.setForeground(new java.awt.Color(153, 153, 153));
        tblanpProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblanpProduct.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblanpProduct.setFillsViewportHeight(true);
        tblanpProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblanpProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblanpProduct);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Product/2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(txtanpId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtanpName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtanpDes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1)))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(btnancSave, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtanpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtanpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtanpDes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnancSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtanpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanpIdActionPerformed

    private void txtanpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanpNameActionPerformed

    private void btnancSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnancSaveMouseClicked
        String name, description;
        if (txtanpName.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Please provide the name...", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Please provide the name...");
        } else {
            name = txtanpName.getText();
            description = txtanpDes.getText();
//            Icon icon = imageIcon.getIcon();
  

                productSet.addProducts(new ProductsImp(name, description, 6, 5.00, "No"));
           

            try {
                Serialization.Serialize(productSet, FILE_NAME_Products);
              
                System.out.println("Add Sucsessfully");
                
            } catch (IOException ex) {
//                Logger.getLogger(AddNewProduct.class.getName()).log(Level.SEVERE, null, ex);
//                JOptionPane.showMessageDialog(this, "Unsuccessful...", "Error", JOptionPane.ERROR_MESSAGE);
                  System.out.println("Add Sucsessfully");
            }

            loadAddProduct(productSet);

        }

    }//GEN-LAST:event_btnancSaveMouseClicked

    private void btnancSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnancSaveActionPerformed

    }//GEN-LAST:event_btnancSaveActionPerformed

    private void tblanpProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblanpProductMouseClicked

//        DefaultTableModel dtm = (DefaultTableModel) tblanpProduct.getModel();
//
//        int row = tblanpProduct.getSelectedRow();
//
//        txtanpId.setText(tblanpProduct.getValueAt(row, 0).toString());
//        txtanpName.setText(tblanpProduct.getValueAt(row, 1).toString());
//        txtanpDes.setText(tblanpProduct.getValueAt(row, 2).toString());
//
//        for (ProductsImp products : productSet) {
//            if (products.getProductNo() == Integer.parseInt(txtanpId.getText())) {
//                BufferedImage bufferedImage = null;
//                try {
//                    InputStream inputStream = new ByteArrayInputStream(products.getImage());
//                    bufferedImage = ImageIO.read(inputStream);
//                } catch (IOException ex) {
//                    System.out.println(ex.getMessage());
//                }
//                Image img = bufferedImage;
//                Image newimg = img.getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
//                ImageIcon imi = new ImageIcon(newimg);
//                imageIcon.setIcon(imi);
//
//                break;
//            }
//
//            products.print();
//        }

    }//GEN-LAST:event_tblanpProductMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    
        private void loadAddProduct(SetOfProducts products) {

        String[] colName = {"ProductID", "Name", "Description", "Unit Price", "Total Quantity", "Avalability"};
        Object[][] object = new Object[products.size()][6];
        int i = 0;
        if (products.size() != 0) {
            for (ProductsImp product : products) {
                object[i][0] = product.getProductNo();
                object[i][1] = product.getName();
                object[i][2] = product.getdescription();
                object[i][3] = product.getPrice();
                object[i][4] = product.getQuantity();
                object[i][5] = product.getAvalability();
                i++;

            }
        }

        DefaultTableModel model = new DefaultTableModel(object, colName) {
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        tblanpProduct.setModel(model);
        tblanpProduct.setRowSorter(new TableRowSorter<TableModel>(model));
        tblanpProduct.setAutoscrolls(true);
        tblanpProduct.getTableHeader().setReorderingAllowed(false);

    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnancSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblanpProduct;
    private javax.swing.JTextField txtanpDes;
    private javax.swing.JTextField txtanpId;
    private javax.swing.JTextField txtanpName;
    // End of variables declaration//GEN-END:variables
}
